const faultTypeToGeneral = {
    "Air Conditioner": "HVAC",
    "Audio": "Audio/Visual",
    "Battery": "Electrical System",
    "Card Access": "Security System",
    "Ceiling": "Building Structure",
    "Central Vacuum": "Appliance",
    "Classroom ICT Support (V/PC)": "IT Support",
    "Computer Support": "IT Support",
    "Laptop Support": "IT Support",
    "Door": "Building Fixture",
    "Window": "Building Fixture",
    "Roller Shutter ": "Building Fixture",
    "Electrical": "Electrical System",
    "Event": "Other",
    "Fence": "Building Exterior",
    "Gate": "Building Exterior",
    "Fire Fighting": "Safety System",
    "Floor": "Building Structure",
    "Genset": "Electrical System",
    "Housekeeping": "Maintenance",
    "Landscaping": "Grounds Maintenance",
    "Landslide": "Grounds Maintenance",
    "Access Road": "Grounds Maintenance",
    "Lift": "Building Transportation",
    "Escalator": "Building Transportation",
    "Lighting": "Electrical System",
    "Meeting Room ICT Support (AV/PC)": "IT Support",
    "MMU WIFI": "Network Infrastructure",
    "Network Support": "Network Infrastructure",
    "Parking Barrier": "Infrastructure",
    "Pest Control": "Maintenance",
    "Printer Support": "IT Support",
    "Projector Support": "IT Support",
    "Rain Down Pipe": "Plumbing",
    "Rectifier": "Electrical System",
    "Roof": "Building Structure",
    "Toilet Accesories": "Plumbing",
    "Toilet Defect": "Plumbing",
    "UPS": "Electrical System",
    "Wall": "Building Structure",
    "Water Pipe": "Plumbing",
    "Water Pump": "Plumbing",
    "Water Tank": "Plumbing",
    "Others": "Other",
  }

  export const getSpecialization = (faultType: string) => {
    return faultTypeToGeneral[faultType as keyof typeof faultTypeToGeneral];
  }