export const equipmentType = [
    { type: "Air Conditioner", equipment: "Split Unit AC" },
    { type: "Air Conditioner", equipment: "Cassette AC" },
    { type: "Air Conditioner", equipment: "VRV System" },
    { type: "Audio", equipment: "PA System Speaker" },
    { type: "Audio", equipment: "Microphone" },
    { type: "Audio", equipment: "Audio Mixer" },
    { type: "Battery", equipment: "UPS Battery" },
    { type: "Battery", equipment: "Car Battery" },
    { type: "Battery", equipment: "Lithium-Ion Battery" },
    { type: "Card Access", equipment: "RFID Card Reader" },
    { type: "Card Access", equipment: "Biometric Scanner" },
    { type: "Card Access", equipment: "Keypad Lock" },
    { type: "Ceiling", equipment: "Ceiling Panel" },
    { type: "Ceiling", equipment: "Ceiling Fan" },
    { type: "Ceiling", equipment: "Recessed Lighting Fixture" },
    { type: "Central Vacuum", equipment: "Vacuum Pump" },
    { type: "Central Vacuum", equipment: "Dust Collection Unit" },
    { type: "Central Vacuum", equipment: "Suction Hose" },
    { type: "Classroom ICT Support (AV/PC)", equipment: "Interactive Whiteboard" },
    { type: "Classroom ICT Support (AV/PC)", equipment: "Projector" },
    { type: "Classroom ICT Support (AV/PC)", equipment: "Desktop Computer" },
    { type: "Computer/Laptop Support", equipment: "Laptop" },
    { type: "Computer/Laptop Support", equipment: "Desktop PC" },
    { type: "Computer/Laptop Support", equipment: "Mouse" },
    { type: "Computer/Laptop Support", equipment: "Keyboard" },
    { type: "Computer/Laptop Support", equipment: "External Monitor" },
    { type: "Door/Window/Roller Shutter", equipment: "Automatic Sliding Door" },
    { type: "Door/Window/Roller Shutter", equipment: "Roller Shutter Motor" },
    { type: "Door/Window/Roller Shutter", equipment: "Window Lock" },
    { type: "Electrical", equipment: "Circuit Breaker" },
    { type: "Electrical", equipment: "Power Socket" },
    { type: "Electrical", equipment: "Electrical Panel" },
    { type: "Event", equipment: "Portable PA System" },
    { type: "Event", equipment: "Stage Lighting" },
    { type: "Event", equipment: "Wireless Microphone" },
    { type: "Facilities/Others", equipment: "Office Chair" },
    { type: "Facilities/Others", equipment: "Whiteboard" },
    { type: "Facilities/Others", equipment: "Notice Board" },
    { type: "Fence/Gate", equipment: "Motorized Gate" },
    { type: "Fence/Gate", equipment: "Chain Link Fence" },
    { type: "Fence/Gate", equipment: "Security Bollards" },
    { type: "Fire Fighting", equipment: "Fire Extinguisher" },
    { type: "Fire Fighting", equipment: "Fire Alarm" },
    { type: "Fire Fighting", equipment: "Sprinkler System" },
    { type: "Floor", equipment: "Vinyl Flooring" },
    { type: "Floor", equipment: "Carpet Tiles" },
    { type: "Floor", equipment: "Wooden Parquet" },
    { type: "Genset", equipment: "Diesel Generator" },
    { type: "Genset", equipment: "Automatic Transfer Switch (ATS)" },
    { type: "Genset", equipment: "Fuel Tank" },
    { type: "Housekeeping", equipment: "Industrial Vacuum Cleaner" },
    { type: "Housekeeping", equipment: "Mop" },
    { type: "Housekeeping", equipment: "Trash Bin" },
    { type: "Landscaping", equipment: "Lawn Mower" },
    { type: "Landscaping", equipment: "Hedge Trimmer" },
    { type: "Landscaping", equipment: "Watering System" },
    { type: "Landslide/Access Road", equipment: "Retaining Wall" },
    { type: "Landslide/Access Road", equipment: "Drainage System" },
    { type: "Landslide/Access Road", equipment: "Guardrail" },
    { type: "Lift/Escalator", equipment: "Passenger Lift" },
    { type: "Lift/Escalator", equipment: "Escalator Handrail" },
    { type: "Lift/Escalator", equipment: "Call Button Panel" },
    { type: "Lighting", equipment: "LED Floodlight" },
    { type: "Lighting", equipment: "Emergency Exit Light" },
    { type: "Lighting", equipment: "Street Light" },
    { type: "Meeting Room ICT Support (AV/PC)", equipment: "Video Conferencing System" },
    { type: "Meeting Room ICT Support (AV/PC)", equipment: "Digital Display" },
    { type: "Meeting Room ICT Support (AV/PC)", equipment: "Wireless Presenter" },
    { type: "MMU WIFI", equipment: "Wireless Access Point" },
    { type: "MMU WIFI", equipment: "Network Router" },
    { type: "MMU WIFI", equipment: "Fiber Optic Cable" },
];