export const equipmentType = [
    { type: "Air Conditioner", equipment: ["Split Unit AC", "Cassette AC", "Ceiling Mounted AC", "Window AC", "VRF System"] },
    { type: "Audo", equipment: ["Speakers", "Microphones", "Amplifiers", "Sound Mixer", "Headphones"] },
    { type: "Battery", equipment: ["Car Battery", "UPS Battery", "AA Battery", "AAA Battery", "Rechargeable Battery"] },
    { type: "Card Access", equipment: ["Card Reader", "Door Controller", "Electric Strike", "Magnetic Lock", "Key Fob"] },
    { type: "Ceiling", equipment: ["Ceiling Fan", "Ceiling Light", "False Ceiling Panel", "Ceiling Board", "Suspended Ceiling Grid"] },
    { type: "Central Vacuum", equipment: ["Vacuum Unit", "Inlet Valve", "Hose", "Wand", "Dust Bag"] },
    { type: "Classroom ICT Support", equipment: ["Projector", "Interactive Whiteboard", "Desktop Computer", "Laptop", "Document Camera"] },
    { type: "Computer Support", equipment: ["Desktop Computer", "Laptop", "Monitor", "Keyboard", "Mouse"] },
    { type: "Laptop Support", equipment: ["Desktop Computer", "Laptop", "Monitor", "Keyboard", "Mouse"] },
    { type: "Door", equipment: ["Door Hinge", "Door Lock", "Window Handle", "Roller Shutter Motor", "Window Frame"] },
    { type: "Window", equipment: ["Door Hinge", "Door Lock", "Window Handle", "Roller Shutter Motor", "Window Frame"] },
    { type: "Roller Shutter ", equipment: ["Door Hinge", "Door Lock", "Window Handle", "Roller Shutter Motor", "Window Frame"] },
    { type: "Electrical", equipment: ["Light Switch", "Power Outlet", "Circuit Breaker", "Wiring", "Electrical Panel"] },
    { type: "Event", equipment: ["Stage Lighting", "Sound System", "Projector Screen", "Chairs", "Tables"] },
    { type: "Fence", equipment: ["Gate Motor", "Fence Panel", "Gate Hinge", "Fence Post", "Security Gate"] },
    { type: "Gate", equipment: ["Gate Motor", "Fence Panel", "Gate Hinge", "Fence Post", "Security Gate"] },
    { type: "Fire Fighting", equipment: ["Fire Extinguisher", "Smoke Detector", "Fire Alarm", "Sprinkler System", "Fire Hose Reel"] },
    { type: "Floor", equipment: ["Floor Tiles", "Carpet", "Parquet Flooring", "Epoxy Flooring", "Floor Drain"] },
    { type: "Genset", equipment: ["Diesel Generator", "Petrol Generator", "Alternator", "Control Panel", "Fuel Tank"] },
    { type: "Housekeeping", equipment: ["Vacuum Cleaner", "Mop", "Broom", "Cleaning Supplies", "Dustbin"] },
    { type: "Landscaping", equipment: ["Lawn Mower", "Trimmer", "Sprinkler System", "Garden Hose", "Shovel"] },
    { type: "Landslide/Access Road", equipment: ["Road Barrier", "Warning Sign", "Drainage System", "Retaining Wall", "Road Surface"] },
    { type: "Access Road", equipment: ["Road Barrier", "Warning Sign", "Drainage System", "Retaining Wall", "Road Surface"] },
    { type: "Lift", equipment: ["Lift Cabin", "Escalator Step", "Motor", "Control Panel", "Safety Sensor"] },
    { type: "Escalator", equipment: ["Lift Cabin", "Escalator Step", "Motor", "Control Panel", "Safety Sensor"] },
    { type: "Lighting", equipment: ["Light Bulb", "Fluorescent Tube", "LED Light", "Street Light", "Emergency Light"] },
    { type: "Meeting Room ICT Support", equipment: ["Projector", "Screen", "Speakers", "Microphone", "Video Conferencing System"] },
    { type: "MMU WIFI", equipment: ["Router", "Access Point", "Network Cable", "Antenna", "Modem"] },
    { type: "Network Support", equipment: ["Router", "Switch", "Firewall", "Server", "Network Cable"] },
    { type: "Parking Barrier", equipment: ["Barrier Gate", "Ticket Dispenser", "Payment Terminal", "Loop Detector", "Access Control System"] },
    { type: "Pest Control", equipment: ["Bait Station", "Insecticide Sprayer", "Traps", "Fogging Machine", "Protective Gear"] },
    { type: "Printer Support", equipment: ["Laser Printer", "Inkjet Printer", "Multifunction Printer", "Toner", "Ink Cartridge"] },
    { type: "Projector Support", equipment: ["Projector Lamp", "Projector Screen", "Projector Mount", "Remote Control", "Cables"] },
    { type: "Rain Down Pipe", equipment: ["Downpipe", "Gutter", "Elbow", "Bracket", "Strainer"] },
    { type: "Rectifier", equipment: ["Diode", "Transformer", "Capacitor", "Heat Sink", "Voltage Regulator"] },
    { type: "Roof", equipment: ["Roof Tiles", "Roof Sheet", "Gutter", "Flashing", "Insulation"] },
    { type: "Toilet Accesories", equipment: ["Toilet Paper Holder", "Soap Dispenser", "Hand Dryer", "Mirror", "Grab Bar"] },
    { type: "Toilet Defect", equipment: ["Toilet Bowl", "Sink", "Faucet", "Flush Valve", "Drainage Pipe"] },
    { type: "UPS", equipment: ["Battery Backup", "Surge Protector", "Power Cord", "Monitoring Software", "Inverter"] },
    { type: "Wall", equipment: ["Paint", "Wallpaper", "Plaster", "Drywall", "Wall Tiles"] },
    { type: "Water Pipe", equipment: ["PVC Pipe", "Copper Pipe", "Valve", "Joint", "Tap"] },
    { type: "Water Pump", equipment: ["Submersible Pump", "Centrifugal Pump", "Booster Pump", "Pressure Tank", "Motor"] },
    { type: "Water Tank", equipment: ["Storage Tank", "Pressure Tank", "Level Sensor", "Inlet Pipe", "Outlet Pipe"] },
    { type: "Others", equipment: ["Chair", "Table", "Whiteboard", "Notice Board", "Waste Bin"] },
  ];