export const faultType = [
    { code: 'AC', type: 'Air Conditioner' },
    { code: 'AUD', type: 'Audio' },
    { code: 'BAT', type: 'Battery' },
    { code: 'CA', type: 'Card Access' },
    { code: 'CEL', type: 'Ceiling' },
    { code: 'CV', type: 'Central Vacuum' },
    { code: 'CICTS', type: 'Classroom ICT Support' },
    { code: 'CMP', type: 'Computer Support' },
    { code: 'LPS', type: 'Laptop Support' },
    { code: 'DR', type: 'Door' },
    { code: 'WIN', type: 'Window' },
    { code: 'RS', type: 'Roller Shutter' },
    { code: 'ELC', type: 'Electrical' },
    { code: 'EVT', type: 'Event' },
    { code: 'FEN', type: 'Fence' },
    { code: 'FF', type: 'Fire Fighting' },
    { code: 'FLR', type: 'Floor' },
    { code: 'GEN', type: 'Genset' },
    { code: 'HK', type: 'Housekeeping' },
    { code: 'LND', type: 'Landscaping' },
    { code: 'LLS', type: 'Landslide' },
    { code: 'AR', type: 'Access Road' },
    { code: 'LFT', type: 'Lift' },
    { code: 'ESC', type: 'Escalator' },
    { code: 'LIT', type: 'Lighting' },
    { code: 'MICTS', type: 'Meeting Room ICT Support' },
    { code: 'MWIFI', type: 'MMU WIFI' },
    { code: 'NET', type: 'Network Support' },
    { code: 'PB', type: 'Parking Barrier' },
    { code: 'PC', type: 'Pest Control' },
    { code: 'PRS', type: 'Printer Support' },
    { code: 'PJS', type: 'Projector Support' },
    { code: 'RDP', type: 'Rain Down Pipe' },
    { code: 'REC', type: 'Rectifier' },
    { code: 'ROF', type: 'Roof' },
    { code: 'TA', type: 'Toilet Accesories' },
    { code: 'TD', type: 'Toilet Defect' },
    { code: 'UPS', type: 'UPS' },
    { code: 'WAL', type: 'Wall' },
    { code: 'WP', type: 'Water Pipe' },
    { code: 'WPM', type: 'Water Pump' },
    { code: 'WTK', type: 'Water Tank' },
];