export const faultType = [
    { code: 'ACM01', type: 'Air Conditioner' },
    { code: 'LIG02', type: 'Audo' },
    { code: 'PLB03', type: 'Battery' },
    { code: 'ELE04', type: 'Card Access' },
    { code: 'WIF05', type: 'Ceiling' },
    { code: 'PRJ06', type: 'Central Vacuum' },
    { code: 'CHW07', type: 'Classroom ICT Support (V/PC)' },
    { code: 'ELV08', type: 'Computer/Laptop Support' },
    { code: 'LAB09', type: 'Door/Window/Roller Shutter ' },
    { code: 'CFD10', type: 'Electrical' },
    { code: 'DLA11', type: 'Event' },
    { code: 'WDM12', type: 'Facilities/Others' },
    { code: 'VSP13', type: 'Fence/Gate' },
    { code: 'FAS14', type: 'Fire Fighting' },
    { code: 'AVF15', type: 'Floor' },
    { code: 'AVF15', type: 'Genset' },
    { code: 'AVF15', type: 'Housekeeping' },
    { code: 'AVF15', type: 'Landscaping' },
    { code: 'AVF15', type: 'Landslide/Access Road' },
    { code: 'AVF15', type: 'Lift/Escalator' },
    { code: 'AVF15', type: 'Lighting' },
    { code: 'AVF15', type: 'Meeting Room ICT Support (AV/PC)' },
    { code: 'AVF15', type: 'MMU WIFI' },
    { code: 'AVF15', type: 'Network Support' },
    { code: 'AVF15', type: 'Parking Barrier' },
    { code: 'AVF15', type: 'Pest Control' },
    { code: 'AVF15', type: 'Printer Support' },
    { code: 'AVF15', type: 'Projector Support' },
    { code: 'AVF15', type: 'Rain Down Pipe' },
    { code: 'AVF15', type: 'Rectifier' },
    { code: 'AVF15', type: 'Roof' },
    { code: 'AVF15', type: 'Toilet Accesories' },
    { code: 'AVF15', type: 'Toilet Defect' },
    { code: 'AVF15', type: 'UPS' },
    { code: 'AVF15', type: 'Wall' },
    { code: 'AVF15', type: 'Water Pipe' },
    { code: 'AVF15', type: 'Water Pump' },
    { code: 'AVF15', type: 'Water Tank' },
]
